version: '3.8'

services:
  reportgene:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: reportgene-app
    ports:
      - "7861:7861"
    volumes:
      # 挂载上传目录（持久化）
      - ./upload:/app/upload
      # 挂载输出目录（持久化）
      - ./output:/app/output
      # 可选：挂载模板文件（便于更新）
      - ./template.docx:/app/template.docx:ro
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:7861')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

